spring:
  datasource:
    url: jdbc:mysql://localhost/springbatch?characterEncoding=UTF-8&useSSH=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:/org/springframework/batch/core/schema-mysql.sql
  batch:
    initialize-schema: always